// ФАЙЛ: src/system/defaultPresets.js

const defaultThemePresets = [
    {
        "id": "preset_cobalt_default",
        "name": "Cobalt Core (Дефолт)",
        "theme": {
            "accentColor": "#66ccff",
            "gradientColors": ["#000000", "#001229"],
            "panelOpacity": 80,
            "gradientAngle": 135,
            "useGradient": true,
            "bgDim": 24,
            "bgBloom": 10,
            "bgFitting": "cover",
            "baseTextColor": "#ced6e0",
            "textColor": "#f5f237",
            "thoughtColor": "#808080",
            "boldColor": "#ffffff",
            "thoughtAltColor": "#a0a0a0",
            "soundColor": "#ff9900",
            "whisperColor": "#cc99ff",
            "fontFamily": "Cinzel",
            "fontSize": 15,
            "enableSmartTracker": false,
            "workspaceWidth": 1400,
            "fullWidth": false
        },
        "chatStyle": "cobalt"
    },
    {
        "id": "preset_koyanskaya_pink",
        "name": "Розовый (Vitch Edition)",
        "theme": {
            "accentColor": "#fe7cb0",
            "gradientColors": ["#140b14", "#352134"],
            "panelOpacity": 60,
            "gradientAngle": 180,
            "useGradient": true,
            "bgDim": 0,
            "bgBloom": 0,
            "bgFitting": "stretch",
            "baseTextColor": "#a3a3a3",
            "textColor": "#fcff2e",
            "thoughtColor": "#6f5958",
            "boldColor": "#5469c0",
            "thoughtAltColor": "#8f0000",
            "soundColor": "#00ff40",
            "whisperColor": "#8000ff",
            "fontFamily": "Georgia, serif",
            "fontSize": 16,
            "enableSmartTracker": true,
            "workspaceWidth": 1500,
            "fullWidth": false
        },
        "chatStyle": "cobalt"
    },
    {
        "id": "preset_blood_red",
        "name": "Кровавый (Вампир)",
        "theme": {
            "accentColor": "#ff3333",
            "gradientColors": ["#190000", "#3d0000", "#0f0000"],
            "panelOpacity": 62,
            "gradientAngle": 180,
            "useGradient": true,
            "bgDim": 0,
            "bgBloom": 0,
            "bgFitting": "stretch",
            "baseTextColor": "#a3a3a3",
            "textColor": "#fcff2e",
            "thoughtColor": "#6f5958",
            "boldColor": "#5469c0",
            "thoughtAltColor": "#8f0000",
            "soundColor": "#00ff40",
            "whisperColor": "#8000ff",
            "fontFamily": "Garamond, serif",
            "fontSize": 16,
            "enableSmartTracker": true,
            "workspaceWidth": 1500,
            "fullWidth": false
        },
        "chatStyle": "cobalt"
    },
    {
        "id": "preset_dracula",
        "name": "Dracula (Классика IDE)",
        "theme": {
            "accentColor": "#bd93f9",
            "gradientColors": ["#282a36", "#44475a"],
            "panelOpacity": 85,
            "gradientAngle": 135,
            "useGradient": true,
            "bgDim": 50,
            "bgBloom": 5,
            "bgFitting": "cover",
            "baseTextColor": "#f8f8f2",
            "textColor": "#bd93f9",
            "thoughtColor": "#6272a4",
            "boldColor": "#ffb86c",
            "thoughtAltColor": "#44475a",
            "soundColor": "#50fa7b",
            "whisperColor": "#f1fa8c",
            "fontFamily": "Consolas, monospace",
            "fontSize": 15,
            "enableSmartTracker": true,
            "workspaceWidth": 1300,
            "fullWidth": false
        },
        "chatStyle": "cobalt"
    },
    {
        "id": "preset_cyberpunk",
        "name": "Night City 2077",
        "theme": {
            "accentColor": "#fce205",
            "gradientColors": ["#000000", "#1a0b1c", "#0f2027"],
            "panelOpacity": 75,
            "gradientAngle": 90,
            "useGradient": true,
            "bgDim": 70,
            "bgBloom": 15,
            "bgFitting": "cover",
            "baseTextColor": "#00ffcc",
            "textColor": "#fce205",
            "thoughtColor": "#4a4a4a",
            "boldColor": "#ff003c",
            "thoughtAltColor": "#7a001a",
            "soundColor": "#00ffff",
            "whisperColor": "#d900ff",
            "fontFamily": "'Lucida Console', Monaco, monospace",
            "fontSize": 15,
            "enableSmartTracker": true,
            "workspaceWidth": 1400,
            "fullWidth": false
        },
        "chatStyle": "cobalt"
    },
    {
        "id": "preset_synthwave",
        "name": "Synthwave '84",
        "theme": {
            "accentColor": "#ff7edb",
            "gradientColors": ["#262335", "#1a1025"],
            "panelOpacity": 70,
            "gradientAngle": 180,
            "useGradient": true,
            "bgDim": 60,
            "bgBloom": 20,
            "bgFitting": "cover",
            "baseTextColor": "#36f9f6",
            "textColor": "#f97e72",
            "thoughtColor": "#6943ff",
            "boldColor": "#fede5d",
            "thoughtAltColor": "#493294",
            "soundColor": "#ff7edb",
            "whisperColor": "#36f9f6",
            "fontFamily": "'Trebuchet MS', sans-serif",
            "fontSize": 16,
            "enableSmartTracker": true,
            "workspaceWidth": 1300,
            "fullWidth": false
        },
        "chatStyle": "cobalt"
    },
    {
        "id": "preset_nord",
        "name": "Nord (Холодный)",
        "theme": {
            "accentColor": "#88c0d0",
            "gradientColors": ["#2e3440", "#3b4252", "#434c5e"],
            "panelOpacity": 90,
            "gradientAngle": 135,
            "useGradient": true,
            "bgDim": 30,
            "bgBloom": 0,
            "bgFitting": "cover",
            "baseTextColor": "#eceff4",
            "textColor": "#8fbcbb",
            "thoughtColor": "#4c566a",
            "boldColor": "#ebcb8b",
            "thoughtAltColor": "#d08770",
            "soundColor": "#a3be8c",
            "whisperColor": "#b48ead",
            "fontFamily": "Tahoma, sans-serif",
            "fontSize": 15,
            "enableSmartTracker": false,
            "workspaceWidth": 1300,
            "fullWidth": false
        },
        "chatStyle": "cobalt"
    },
    {
        "id": "preset_matrix",
        "name": "Matrix Hack",
        "theme": {
            "accentColor": "#00ff41",
            "gradientColors": ["#000000", "#001100"],
            "panelOpacity": 80,
            "gradientAngle": 180,
            "useGradient": true,
            "bgDim": 90,
            "bgBloom": 5,
            "bgFitting": "cover",
            "baseTextColor": "#008f11",
            "textColor": "#00ff41",
            "thoughtColor": "#003b00",
            "boldColor": "#ffffff",
            "thoughtAltColor": "#002200",
            "soundColor": "#00ff41",
            "whisperColor": "#008f11",
            "fontFamily": "'Courier New', Courier, monospace",
            "fontSize": 14,
            "enableSmartTracker": true,
            "workspaceWidth": 1500,
            "fullWidth": true
        },
        "chatStyle": "cobalt"
    },
    {
        "id": "preset_pure_oled",
        "name": "OLED Pitch Black",
        "theme": {
            "accentColor": "#ffffff",
            "gradientColors": ["#000000", "#000000"],
            "panelOpacity": 100,
            "gradientAngle": 0,
            "useGradient": false,
            "bgDim": 100,
            "bgBloom": 0,
            "bgFitting": "cover",
            "baseTextColor": "#a0a0a0",
            "textColor": "#ffffff",
            "thoughtColor": "#404040",
            "boldColor": "#cccccc",
            "thoughtAltColor": "#303030",
            "soundColor": "#888888",
            "whisperColor": "#555555",
            "fontFamily": "Arial, Helvetica, sans-serif",
            "fontSize": 15,
            "enableSmartTracker": false,
            "workspaceWidth": 1200,
            "fullWidth": false
        },
        "chatStyle": "cobalt"
    }
];

module.exports = { defaultThemePresets };