// ФАЙЛ: src/system/defaultPresets.js

const defaultThemePresets = [
    {
        "id": "preset_cobalt_default",
        "name": "Cobalt Core (Оригинал)",
        "theme": {
            "accentColor": "#66ccff",
            "gradientColors": ["#000000", "#001229"],
            "panelOpacity": 80,
            "gradientAngle": 135,
            "useGradient": true,
            "bgDim": 24,
            "bgBloom": 10,
            "bgFitting": "cover",
            "baseTextColor": "#ced6e0",
            "textColor": "#f5f237",
            "thoughtColor": "#808080",
            "boldColor": "#ffffff",
            "thoughtAltColor": "#a0a0a0",
            "soundColor": "#ff9900",
            "whisperColor": "#cc99ff",
            "fontFamily": "Cinzel",
            "fontSize": 15,
            "enableSmartTracker": false,
            "workspaceWidth": 1400,
            "fullWidth": false
        },
        "chatStyle": "cobalt"
    },
    {
        "id": "preset_cyberpunk_2077",
        "name": "Night City (Cyberpunk)",
        "theme": {
            "accentColor": "#fce205",
            "gradientColors": ["#050505", "#140b1c", "#0f2027"],
            "panelOpacity": 85,
            "gradientAngle": 45,
            "useGradient": true,
            "bgDim": 70,
            "bgBloom": 15,
            "bgFitting": "cover",
            "baseTextColor": "#00ffcc",
            "textColor": "#fce205",
            "thoughtColor": "#696969",
            "boldColor": "#ff003c",
            "thoughtAltColor": "#8a1a36",
            "soundColor": "#00ffff",
            "whisperColor": "#d900ff",
            "fontFamily": "'Lucida Console', monospace",
            "fontSize": 14,
            "enableSmartTracker": true,
            "workspaceWidth": 1300,
            "fullWidth": false
        },
        "chatStyle": "cyberpunk"
    },
    {
        "id": "preset_warhammer_40k",
        "name": "Darktide (Warhammer 40k)",
        "theme": {
            "accentColor": "#a89456",
            "gradientColors": ["#1b211a", "#2d3b2e", "#111111"],
            "panelOpacity": 95,
            "gradientAngle": 180,
            "useGradient": true,
            "bgDim": 53,
            "bgBloom": 10,
            "bgFitting": "cover",
            "baseTextColor": "#c7cba8",
            "textColor": "#ffffff",
            "thoughtColor": "#969a7c",
            "boldColor": "#ffffff",
            "thoughtAltColor": "#577058",
            "soundColor": "#a89456",
            "whisperColor": "#7a8a7a",
            "fontFamily": "Cinzel",
            "fontSize": 15,
            "enableSmartTracker": true,
            "workspaceWidth": 1400,
            "fullWidth": false
        },
        "chatStyle": "warhammer"
    },
    {
        "id": "preset_grimdark_fantasy",
        "name": "True Grimdark",
        "theme": {
            "accentColor": "#8a0303",
            "gradientColors": ["#0a0505", "#1c0a0a", "#050202"],
            "panelOpacity": 95,
            "gradientAngle": 135,
            "useGradient": true,
            "bgDim": 85,
            "bgBloom": 10,
            "bgFitting": "cover",
            "baseTextColor": "#a8a095",
            "textColor": "#c2b280",
            "thoughtColor": "#665252",
            "boldColor": "#ff1a1a",
            "thoughtAltColor": "#3d2e2e",
            "soundColor": "#d46a00",
            "whisperColor": "#5e4b66",
            "fontFamily": "Cinzel",
            "fontSize": 16,
            "enableSmartTracker": true,
            "workspaceWidth": 1350,
            "fullWidth": false
        },
        "chatStyle": "grimdark"
    },
    {
        "id": "preset_roguetrader",
        "name": "Rogue Trader (WH40K)",
        "theme": {
            "accentColor": "#4ade80",
            "gradientColors": ["#161914", "#22271e", "#10120f"],
            "panelOpacity": 95,
            "gradientAngle": 180,
            "useGradient": true,
            "bgDim": 85,
            "bgBloom": 5,
            "bgFitting": "cover",
            "baseTextColor": "#e1d7bd",
            "textColor": "#e6c365",
            "thoughtColor": "#738066",
            "boldColor": "#ff4d4d",
            "thoughtAltColor": "#4d5940",
            "soundColor": "#4ade80",
            "whisperColor": "#85947a",
            "fontFamily": "Georgia, serif",
            "fontSize": 15,
            "enableSmartTracker": true,
            "workspaceWidth": 1400,
            "fullWidth": false
        },
        "chatStyle": "roguetrader"
    },
    {
        "id": "preset_starwars_sith",
        "name": "Dark Side (Star Wars)",
        "theme": {
            "accentColor": "#ff0000",
            "gradientColors": ["#000000", "#110000", "#220000"],
            "panelOpacity": 90,
            "gradientAngle": 135,
            "useGradient": true,
            "bgDim": 80,
            "bgBloom": 20,
            "bgFitting": "cover",
            "baseTextColor": "#cccccc",
            "textColor": "#ff4444",
            "thoughtColor": "#666666",
            "boldColor": "#ffffff",
            "thoughtAltColor": "#444444",
            "soundColor": "#ffcc00",
            "whisperColor": "#5555aa",
            "fontFamily": "Consolas, monospace",
            "fontSize": 15,
            "enableSmartTracker": true,
            "workspaceWidth": 1500,
            "fullWidth": false
        },
        "chatStyle": "starwars"
    },
    {
        "id": "preset_got_stark",
        "name": "Winter is Coming (GoT)",
        "theme": {
            "accentColor": "#aaccff",
            "gradientColors": ["#0d1117", "#1a2530"],
            "panelOpacity": 85,
            "gradientAngle": 180,
            "useGradient": true,
            "bgDim": 40,
            "bgBloom": 0,
            "bgFitting": "cover",
            "baseTextColor": "#d9e2ec",
            "textColor": "#ffffff",
            "thoughtColor": "#8a96a3",
            "boldColor": "#66a3ff",
            "thoughtAltColor": "#4a5a6a",
            "soundColor": "#ffffff",
            "whisperColor": "#88c0d0",
            "fontFamily": "Georgia, serif",
            "fontSize": 16,
            "enableSmartTracker": true,
            "workspaceWidth": 1200,
            "fullWidth": false
        },
        "chatStyle": "got"
    },
    {
        "id": "preset_dragonage_blood",
        "name": "Blood Mage (Dragon Age)",
        "theme": {
            "accentColor": "#8b0000",
            "gradientColors": ["#000000", "#1a0000"],
            "panelOpacity": 90,
            "gradientAngle": 90,
            "useGradient": true,
            "bgDim": 60,
            "bgBloom": 10,
            "bgFitting": "cover",
            "baseTextColor": "#c0a080",
            "textColor": "#ffcccc",
            "thoughtColor": "#665544",
            "boldColor": "#ff0000",
            "thoughtAltColor": "#443322",
            "soundColor": "#ffaa00",
            "whisperColor": "#993333",
            "fontFamily": "'Palatino Linotype', serif",
            "fontSize": 16,
            "enableSmartTracker": true,
            "workspaceWidth": 1350,
            "fullWidth": false
        },
        "chatStyle": "dragonage"
    },
    {
        "id": "preset_hogwarts_slytherin",
        "name": "Serpent (Hogwarts)",
        "theme": {
            "accentColor": "#2a623d",
            "gradientColors": ["#0b120f", "#051f0f", "#000000"],
            "panelOpacity": 90,
            "gradientAngle": 135,
            "useGradient": true,
            "bgDim": 50,
            "bgBloom": 5,
            "bgFitting": "cover",
            "baseTextColor": "#d1c4a9",
            "textColor": "#e8dcc4",
            "thoughtColor": "#8b9c8b",
            "boldColor": "#d4af37",
            "thoughtAltColor": "#4a5d4e",
            "soundColor": "#2a623d",
            "whisperColor": "#99b399",
            "fontFamily": "Garamond, serif",
            "fontSize": 16,
            "enableSmartTracker": true,
            "workspaceWidth": 1200,
            "fullWidth": false
        },
        "chatStyle": "hogwarts"
    },
    {
        "id": "preset_marvel_hud",
        "name": "Stark HUD (Marvel)",
        "theme": {
            "accentColor": "#00ffff",
            "gradientColors": ["#050a14", "#0a1428"],
            "panelOpacity": 70,
            "gradientAngle": 180,
            "useGradient": true,
            "bgDim": 65,
            "bgBloom": 20,
            "bgFitting": "cover",
            "baseTextColor": "#66ccff",
            "textColor": "#ffffff",
            "thoughtColor": "#336699",
            "boldColor": "#ff3333",
            "thoughtAltColor": "#224466",
            "soundColor": "#ff9900",
            "whisperColor": "#00ffff",
            "fontFamily": "'Roboto', sans-serif",
            "fontSize": 15,
            "enableSmartTracker": true,
            "workspaceWidth": 1000,
            "fullWidth": false
        },
        "chatStyle": "marvel"
    },
    {
        "id": "preset_fantasy_rpg",
        "name": "DnD Classic (Fantasy)",
        "theme": {
            "accentColor": "#d4af37",
            "gradientColors": ["#1a120b", "#2a1e12"],
            "panelOpacity": 95,
            "gradientAngle": 135,
            "useGradient": true,
            "bgDim": 30,
            "bgBloom": 0,
            "bgFitting": "cover",
            "baseTextColor": "#d3c4a8",
            "textColor": "#ffffff",
            "thoughtColor": "#8b7e66",
            "boldColor": "#d4af37",
            "thoughtAltColor": "#5c503f",
            "soundColor": "#ff4444",
            "whisperColor": "#8da399",
            "fontFamily": "Georgia, serif",
            "fontSize": 16,
            "enableSmartTracker": true,
            "workspaceWidth": 1300,
            "fullWidth": false
        },
        "chatStyle": "fantasy"
    },
    {
        "id": "preset_bubbles_messenger",
        "name": "Messenger (Bubbles)",
        "theme": {
            "accentColor": "#0088cc",
            "gradientColors": ["#111111", "#1a1a1a"],
            "panelOpacity": 100,
            "gradientAngle": 0,
            "useGradient": true,
            "bgDim": 50,
            "bgBloom": 0,
            "bgFitting": "cover",
            "baseTextColor": "#e0e0e0",
            "textColor": "#ffffff",
            "thoughtColor": "#888888",
            "boldColor": "#66ccff",
            "thoughtAltColor": "#555555",
            "soundColor": "#00ffaa",
            "whisperColor": "#cc99ff",
            "fontFamily": "Arial, sans-serif",
            "fontSize": 14,
            "enableSmartTracker": false,
            "workspaceWidth": 900,
            "fullWidth": false
        },
        "chatStyle": "bubbles"
    },
    {
        "id": "preset_zen_writer",
        "name": "Writer's Zen (Минимализм)",
        "theme": {
            "accentColor": "#ffffff",
            "gradientColors": ["#000000", "#000000"],
            "panelOpacity": 100,
            "gradientAngle": 0,
            "useGradient": false,
            "bgDim": 100,
            "bgBloom": 0,
            "bgFitting": "cover",
            "baseTextColor": "#999999",
            "textColor": "#cccccc",
            "thoughtColor": "#555555",
            "boldColor": "#ffffff",
            "thoughtAltColor": "#333333",
            "soundColor": "#777777",
            "whisperColor": "#666666",
            "fontFamily": "'Times New Roman', Times, serif",
            "fontSize": 18,
            "enableSmartTracker": false,
            "workspaceWidth": 1100,
            "fullWidth": false
        },
        "chatStyle": "zen"
    },
    {
        "id": "preset_classic_terminal",
        "name": "Retro Terminal (Classic)",
        "theme": {
            "accentColor": "#00ff00",
            "gradientColors": ["#050505", "#0a0a0a"],
            "panelOpacity": 100,
            "gradientAngle": 0,
            "useGradient": false,
            "bgDim": 90,
            "bgBloom": 5,
            "bgFitting": "cover",
            "baseTextColor": "#00cc00",
            "textColor": "#00ff00",
            "thoughtColor": "#005500",
            "boldColor": "#ffffff",
            "thoughtAltColor": "#003300",
            "soundColor": "#ffff00",
            "whisperColor": "#008800",
            "fontFamily": "'Courier New', Courier, monospace",
            "fontSize": 14,
            "enableSmartTracker": false,
            "workspaceWidth": 1600,
            "fullWidth": true
        },
        "chatStyle": "classic"
    },
    {
        "id": "preset_baldursgate3",
        "name": "Faerûn (BG3)",
        "theme": {
            "accentColor": "#c1a673",
            "gradientColors": ["#14100c", "#0a0705", "#050403"],
            "panelOpacity": 95,
            "gradientAngle": 180,
            "useGradient": true,
            "bgDim": 80,
            "bgBloom": 10,
            "bgFitting": "cover",
            "baseTextColor": "#d8ceb9",
            "textColor": "#c1a673",
            "thoughtColor": "#8a7e6a",
            "boldColor": "#ff6666",
            "thoughtAltColor": "#594f3e",
            "soundColor": "#66ccff",
            "whisperColor": "#a688cc",
            "fontFamily": "Georgia, serif",
            "fontSize": 15,
            "enableSmartTracker": true,
            "workspaceWidth": 1350,
            "fullWidth": false
        },
        "chatStyle": "bg3"
    },
    {
        "id": "preset_visual_novel",
        "name": "Visual Novel (Anime)",
        "theme": {
            "accentColor": "#ff77aa",
            "gradientColors": ["rgba(20, 15, 30, 0.8)", "rgba(10, 5, 15, 0.85)"],
            "panelOpacity": 85,
            "gradientAngle": 135,
            "useGradient": true,
            "bgDim": 60,
            "bgBloom": 15,
            "bgFitting": "cover",
            "baseTextColor": "#ffffff",
            "textColor": "#ff77aa",
            "thoughtColor": "#bbaadd",
            "boldColor": "#ffdd55",
            "thoughtAltColor": "#8877aa",
            "soundColor": "#55ccff",
            "whisperColor": "#dd99ff",
            "fontFamily": "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
            "fontSize": 17,
            "enableSmartTracker": true,
            "workspaceWidth": 1300,
            "fullWidth": false
        },
        "chatStyle": "vn"
    },
    {
        "id": "preset_kawaii_pink",
        "name": "Dark Kawaii (Kuromi)",
        "theme": {
            "accentColor": "#ff77bb",
            "gradientColors": ["#1a0f14", "#20131a", "#261520"],
            "panelOpacity": 90,
            "gradientAngle": 135,
            "useGradient": true,
            "bgDim": 75,
            "bgBloom": 15,
            "bgFitting": "cover",
            "baseTextColor": "#e6d5e6",
            "textColor": "#ff77bb",
            "thoughtColor": "#aa77cc",
            "boldColor": "#ff3377",
            "thoughtAltColor": "#cc99dd",
            "soundColor": "#ff99cc",
            "whisperColor": "#dd99ff",
            "fontFamily": "'Quicksand', 'Nunito', 'Comic Sans MS', sans-serif",
            "fontSize": 15,
            "enableSmartTracker": true,
            "workspaceWidth": 1250,
            "fullWidth": false
        },
        "chatStyle": "kawaii"
    },
];

module.exports = { defaultThemePresets };